name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  

      - name: Restore dependencies
        run: dotnet restore CyberSecurityAwareness/CyberSecurityAwareness/CyberSecurityAwareness.csproj

      - name: Build project
        run: dotnet build CyberSecurityAwareness/CyberSecurityAwareness/CyberSecurityAwareness.csproj --no-restore

      - name: Run tests
        run: dotnet test CyberSecurityAwareness/CyberSecurityAwareness/CyberSecurityAwareness.csproj --no-build --verbosity normal
